# docker-compose.yml

# version: '3.9'

services:
  web:
    build:
      context: ./backend
    container_name: smart_home_web
    command: ["./entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
  
  worker:
    build:
      context: ./backend
    container_name: smart_home_worker
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env

  beat:
    build:
      context: ./backend
    container_name: smart_home_beat
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:

